name: Android CICD

on:
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: gradle
    - name: Unit Test
      run: ./gradlew test --stacktrace
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: gradle
    - name: Build
      run: ./gradlew assembleDebug
      
  generate-aab:
    runs-on: ubuntu-latest
    steps:
    # チェックアウト
    - uses: actions/checkout@v3

    # JDKのセットアップ
    - name: set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: gradle

    # 依存関係の出力
    - name: Displays the Android dependencies of the project
      run: ./gradlew androidDependencies

    # キーストアのデコード
    - name: Decode Keystore
      run: echo ${{ secrets.ENCODED_RELEASE_KEYSTORE }} | base64 --decode > ./app/release.keystore

    # AABの生成
    - name: Generate AAB
      run: ./gradlew :app:bundleRelease
      env:
        RELEASE_KEYSTORE_STORE_PASSWORD: ${{ secrets.RELEASE_KEYSTORE_STORE_PASSWORD }}
        RELEASE_KEYSTORE_KEY_PASSWORD: ${{ secrets.RELEASE_KEYSTORE_KEY_PASSWORD }}

    # AABのアップロード
    - name: Upload AAB Artifact
      uses: actions/upload-artifact@v3
      with:
        name: mt-aab
        path: app/build/outputs/bundle/productionRelease/app-production-release.aab
        if-no-files-found: error
